### ISSUE TITLE
Search results contain broken links

### ISSUE THREAD

**Issue by aivarannamaa** [vladris/tinkerer#104]
Example: http://thonny.org/blog/search.html?q=version

Instead of

http://thonny.org/blog/2017/01/05/version_2_0_7.rst.html?highlight=version

the link should be

http://thonny.org/blog/2017/01/05/version_2_0_7.html?highlight=version

**Comment by vladris** [comment]
Seems to be an upstream regression. I wasn't able to repro with the version of Sphinx I was running (1.3.3), but after an upgrade to latest Sphinx (1.5.1) I do see the extra rst appearing in links. I'll need to dig a bit through the Sphinx updates to understand what broke.
