### ISSUE TITLE
Remove posts

### ISSUE THREAD

**Issue by rmk135** [vladris/tinkerer#105]
Hello there,

Is there a way to remove posts?

PS: thank you for this really awesome application :)

Thanks,
Roman

**Comment by vladris** [comment]
You can demote a post to draft then simply rm the file from the drafts directory. Use --draft <path to post>. See here for more info: http://tinkerer.me/doc/command_line.html

I'm glad you enjoy Tinkerer!

**Comment by rmk135** [comment]
Hey @vladris ,

Thanks for response, it works well for me.

Roman
