### ISSUE TITLE
more complete message file for german included (tinkerer.mo)

### ISSUE THREAD

**Issue by KarstenSchulz** [vladris/tinkerer#85]
Hi!

Below is the source for a more complete german localization if the message file in locale/de/LC_MESSAGES. Please use it as you like it.

msgid ""
msgstr ""
"Project-Id-Version: Tinkerer 0.4b\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2012-08-18 20:13+0100\n"
"PO-Revision-Date: 2012-08-18 20:20+0100\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: de <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.6\n"
"X-Language: de_DE\n"
"X-Source-Language: en_US\n"

msgid "%B %d, %Y"
msgstr "%d. %B %Y"

msgid "&copy; Copyright %(copyright)s."
msgstr "&copy; Copyright %(copyright)s."

msgid "&copy; Copyright %(copyright)s. "
msgstr "&copy; Copyright %(copyright)s. "

msgid "About these documents"
msgstr "Über diese Dokumente"

msgid "Blog Archive"
msgstr "Archiv"

msgid "Categories"
msgstr "Kategorien"

msgid "Copyright"
msgstr "Copyright"

msgid "Filed under"
msgstr "Kategorien"

msgid "Filed under <span class=\"title_category\">%s</span>"
msgstr "Artikel mit Kategorie: <span class=\"title_category\">%s</span>"

msgid ""
"From here you can search these documents. Enter your search\n"
"    words into the box below and click \"search\". Note that the search\n"
"    function will automatically search for all of the words. Pages\n"
"    containing fewer words won't appear in the result list."
msgstr ""
"From here you can search these documents. Enter your search\n"
"    words into the box below and click \"search\". Note that the search\n"
"    function will automatically search for all of the words. Pages\n"
"    containing fewer words won't appear in the result list."

msgid "Hide Search Matches"
msgstr "Fundstellen verbergen"

msgid "Home"
msgstr "Startseite"

msgid "Index"
msgstr "Index"

msgid "Javascript must be enabled to see this e-mail address"
msgstr "Um diese E-Mail-Adresse zu sehen, muss Javascript aktiviert sein"

msgid "Newer"
msgstr "Früher"

msgid "Older"
msgstr "Später"

msgid "Page %d"
msgstr "Seite %d"

msgid "Permalink to this definition"
msgstr "Permalink zu dieser Definition "

msgid "Permalink to this headline"
msgstr "Permalink zu dieser Überschrift"

msgid ""
"Please activate JavaScript to enable the search\n"
"    functionality."
msgstr ""
"Bitte aktivieren Sie JavaScript, um die Suchfunktion\n"
"    zu nutzen."

msgid "Posted by"
msgstr "Von"

msgid "Posts tagged with <span class=\"title_tag\">%s</span>"
msgstr "Artikel mit Schlagwort: <span class=\"title_tag\">%s</span>"

msgid "Read more..."
msgstr "Weiter lesen..."

msgid "Recent Posts"
msgstr "Aktuell"

msgid "Search"
msgstr "Suche"

msgid "Search Results"
msgstr "Suchergebnisse"

msgid "Search within %(docstitle)s"
msgstr "Suche innerhalb %(docstitle)s"

msgid "Tags"
msgstr "Schlagwörter"

msgid "Tags Cloud"
msgstr "Tags Cloud"

msgid "Your search did not match any results."
msgstr "Die Suche hat nichts gefunden."

msgid "search"
msgstr "suchen"

**Comment by vladris** [comment]
Could you please send a PR so it can be easily diffed with what's currently there?

**Comment by KarstenSchulz** [comment]
will send a PR.
